# Generated by Django 5.1.2 on 2024-10-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webtoons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webtoon",
            name="characters",
            field=models.TextField(),
        ),
    ]
